easy_admin:
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            form:
                fields:
                    - "username"
                    - "email"
                    - "raisonSociale"
                    - "ville"
                    - "password"
                    -  property: 'roles'
                       type: 'choice'
                       type_options:
                           mapped: true
                           expanded: true
                           multiple: true
                           choices: { 'CLIENT': 'ROLE_CLIENT', 'MAGASIN': 'ROLE_MAGASIN' }
                    - property: 'password'
                      type: 'repeated'
                      type_options:
                           type: Symfony\Component\Form\Extension\Core\Type\PasswordType
                           required: true
                           first_options: { label: 'MDP 1' }
                           second_options: { label: 'MDP 2' }
                    - "confirmationToken"
            
        Client:
            class: App\Entity\Client
            form:
                fields:
                    - "sujet"
                    - "projet"
                    - { property: 'imageFile', type: 'file' }
                    - { property : 'pdfFile' ,  type : 'vich_file' }
            list:
                fields:
                    - "sujet"
                    - "projet"
                    - { property: 'image', type: 'image', base_path: '%app.path.client_images%' }
                    - { property : 'pdf' ,  template : 'pdf.html.twig' ,  base_path : '%app.path.client_pdf%' }
                    
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.client_images%' } 
                    - { property : 'pdf' ,  template : 'pdf.html.twig' ,  base_path : '%app.path.client_pdf%' }
            
                    
                    
        Magasin:
            class: App\Entity\Magasin
            form:
                fields:
                    - "sujet"
                    - "projet"
                    - { property: 'imageFile', type: 'file' }
                    - { property: 'pdfFile',  type: 'vich_file' }
            list:
                fields:
                    - "sujet"
                    - "projet"
                    - { property: 'image', type: 'image', base_path: '%app.path.magasin_images%' }
                    - { property: 'pdf',  template: 'pdf.html.twig',  base_path: '%app.path.magasin_pdf%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.magasin_images%' }
                    - { property: 'pdf',  template: 'pdf.html.twig',  base_path: '%app.path.magasin_pdf%' }
            
    site_name: 'AD-INSTALLATIONS'
    
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@VichUploader/Form/fields.html.twig'





























