vich_uploader:
    db_driver: orm

    mappings:
        client:
            uri_prefix:         '%app.path.client%'
            upload_destination: '%kernel.project_dir%/public/images/client'
            
        magasin:
            uri_prefix:         '%app.path.magasin%'
            upload_destination: '%kernel.project_dir%/public/images/magasin'
