vich_uploader:
    db_driver: orm

    mappings:
        client_images:
            uri_prefix:         '%app.path.client_images%'
            upload_destination: '%kernel.project_dir%/public/%app.path.client_images%'
#            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
        magasin_images:
            uri_prefix:         '%app.path.magasin_images%'
            upload_destination: '%kernel.project_dir%/public/%app.path.magasin_images%'
#            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
            
        client_pdf:
            uri_prefix:         /pdf/client
            upload_destination: '%kernel.project_dir%/public/pdf/client'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
        magasin_pdf:
            uri_prefix:         /pdf/magasin
            upload_destination: '%kernel.project_dir%/public/pdf/magasin'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

